apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: rossi-hkedevops
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: rossi-hkedevops
    spec:
      containers:
      - name: rossi-hkedevops
        image: docker.io/pleungdev/rossi-hkedevops:$BUILD_ID
        ports:
        - containerPort: 40017
---
apiVersion: v1
kind: Service
metadata:
  name: rossi-hkedevops
spec:
  type: LoadBalancer
  ports:
  - port: 3000
  selector:
    app: rossi-hkedevops
